import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for the robotics textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 - Robot Operating System',
      items: [
        'module1-ros2/module1-ros2-chapter1',
        'module1-ros2/module1-ros2-chapter2',
        'module1-ros2/module1-ros2-chapter3',
        'module1-ros2/module1-ros2-chapter4',
        'module1-ros2/module1-ros2-chapter5'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo - Physics Simulation',
      items: [
        'module2-gazebo/module2-gazebo-chapter1',
        'module2-gazebo/module2-gazebo-chapter2',
        'module2-gazebo/module2-gazebo-chapter3',
        'module2-gazebo/module2-gazebo-chapter4',
        'module2-gazebo/module2-gazebo-chapter5'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: Isaac Sim - NVIDIA Robotics Platform',
      items: [
        'module3-isaac/module3-isaac-chapter1',
        'module3-isaac/module3-isaac-chapter2',
        'module3-isaac/module3-isaac-chapter3',
        'module3-isaac/module3-isaac-chapter4',
        'module3-isaac/module3-isaac-chapter5'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: VLA - Vision-Language-Action Models',
      items: [
        'module4-vla/module4-vla-chapter1',
        'module4-vla/module4-vla-chapter2',
        'module4-vla/module4-vla-chapter3',
        'module4-vla/module4-vla-chapter4',
        'module4-vla/module4-vla-chapter5'
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
